spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hrm_system
    username: postgres
    password: sestruha
    driver-class-name: org.postgresql.Driver

  app:
    jwt:
      secret: super-secret-key-should-be-longer-than-32chars

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.yaml

server:
  port: 8080
